{
 "openapi": "3.0.1",
 "info": {
  "title": "rail API Specification",
  "description": "Welcome to the rail Developer Guide!\n",
  "version": "1.0.7"
 },
 "servers": [
  {
   "url": "https://sandbox.layer2financial.com/api",
   "description": "Sandbox - Stable API Instance"
  },
  {
   "url": "https://platform.layer2financial.com/api",
   "description": "Production - Stable API Instance"
  }
 ],
 "tags": [
  {
   "name": "Applications",
   "description": "Customer application (onboarding) management"
  },
  {
   "name": "Accounts/Deposits",
   "description": "Deposit accounts creation and management functions"
  },
  {
   "name": "Accounts/Payments",
   "description": "Payment accounts creation and management functions"
  },
  {
   "name": "Counterparty",
   "description": "Counterparty creation and management functions, including remote linking"
  },
  {
   "name": "Customers",
   "description": "Customer management and servicing functions to allow clients to onboard, manage and maintain customers"
  },
  {
   "name": "Deposits",
   "description": "Deposits are used to move external funds into platform managed accounts"
  },
  {
   "name": "Documents",
   "description": "Document uploading and management functions"
  },
  {
   "name": "Exchanges",
   "description": "Exchanges are used to convert funds from one currency to another. This is achieved by moving money between 2 platform accounts that are denominated in different currencies. We have eliminated the complexity of traditional currency trading."
  },
  {
   "name": "Transactions",
   "description": "Transactions are created to record the movement of funds between accounts. These can be used to record a transfer, a deposit, a withdrawal or a settlement."
  },
  {
   "name": "Transfers",
   "description": "Transfer are used to move funds between two platform managed accounts that are denominated in the same currency. Where possible, these are always performed *offchain*. "
  },
  {
   "name": "Withdrawals",
   "description": "Move funds from a platform managed account to an external counter party"
  },
  {
   "name": "Settlements",
   "description": "Settlement services for funds confirmation and reconciliation"
  },
  {
   "name": "Subscriptions (Webhooks)",
   "description": "Manage your callback (webhook) subscriptions"
  }
 ],
 "paths": {
  "/v1/withdrawals": {
   "post": {
    "tags": [
     "Withdrawals"
    ],
    "summary": "Create Withdrawal",
    "description": "Request a new withdrawal. On successful request, the withdrawal must be accepted before it is queued for execution. Withdrawals accepted before ",
    "operationId": "createWithdrawal",
    "security": [
     {
      "OAuth2Flow": [
       "withdrawals:write"
      ]
     }
    ]
   }
  },
  "/v1/withdrawals/{withdrawal_id}/accept": {
   "post": {
    "tags": [
     "Withdrawals"
    ],
    "summary": "Accept Withdrawal",
    "description": "Accept a withdrawal. This will execute the withdrawal and may not be reversible",
    "operationId": "acceptWithdrawal",
    "security": [
     {
      "OAuth2Flow": [
       "withdrawals:write"
      ]
     }
    ]
   }
  },
  "/v1/transfers": {
   "post": {
    "tags": [
     "Transfers"
    ],
    "summary": "Create Transfer",
    "description": "Request a new transfer. The transfer must be accepted prior to executing",
    "operationId": "createTransfer",
    "security": [
     {
      "OAuth2Flow": [
       "transfers:write"
      ]
     }
    ]
   }
  },
  "/v1/transfers/{transfer_id}/accept": {
   "post": {
    "tags": [
     "Transfers"
    ],
    "summary": "Accept Transfer",
    "description": "Accept a requested transfer. This will execute the transfer and may not be reversible depending on the owner of the destination account",
    "operationId": "confirmTransfer",
    "security": [
     {
      "OAuth2Flow": [
       "transfers:write"
      ]
     }
    ]
   }
  },
  "/v1/subscriptions": {
   "get": {
    "tags": [
     "Subscriptions (Webhooks)"
    ],
    "summary": "Get Subscriptions",
    "description": "Return all subscriptions",
    "operationId": "getSubscriptions",
    "security": [
     {
      "OAuth2Flow": [
       "subscriptions:read"
      ]
     }
    ]
   },
   "post": {
    "tags": [
     "Subscriptions (Webhooks)"
    ],
    "summary": "Create Subscription",
    "description": "Creates a new event call back subscription",
    "operationId": "createSubscription",
    "security": [
     {
      "OAuth2Flow": [
       "subscriptions:write"
      ]
     }
    ]
   }
  },
  "/v1/exchanges/{exchange_id}/accept": {
   "post": {
    "tags": [
     "Exchanges"
    ],
    "summary": "Accept Exchange",
    "description": "Accept an exchange quote. This will execute the exchange and is not reversible",
    "operationId": "acceptExchange",
    "security": [
     {
      "OAuth2Flow": [
       "exchanges:write"
      ]
     }
    ]
   }
  },
  "/v1/exchanges/quote": {
   "post": {
    "tags": [
     "Exchanges"
    ],
    "summary": "Create Exchange (Quote)",
    "description": "Requesting an exchange is non binding, you can request as many exchanges as needed. Typically within your user experience tier, you are expected to poll this endpoint periodically when showing users quotes (e.g. every 3 seconds). When you are ready to accept a quote, see the [accept exchange](#operation/acceptExchange) endpoint. \n\nNote: Not all custodians support all order types. Where the order type is not possible (Quote/Market/Fix Destination/ Fix Source) an error will b[...]",
    "operationId": "createExchangeQuote",
    "security": [
     {
      "OAuth2Flow": [
       "exchanges:write"
      ]
     }
    ]
   }
  },
  "/v1/exchanges/market": {
   "post": {
    "tags": [
     "Exchanges"
    ],
    "summary": "Create Exchange (Market)",
    "description": "When requesting a market exchange, the quote received is indicative ONLY. This represents an approximate  rate from our liquidity providers. On accepting a market exchange the trade is performed at the current market rate which will be different to the quote presented to you.\n\nNote: Not all custodians support all order types. Where the order type is not possible (Quote/Market/Fix Destination/ Fix Source) an error will be returned.",
    "operationId": "createExchangeMarket",
    "security": [
     {
      "OAuth2Flow": [
       "exchanges:write"
      ]
     }
    ]
   }
  },
  "/v1/documents/{document_id}": {
   "post": {
    "tags": [
     "Documents"
    ],
    "summary": "Upload Document",
    "description": "Uploads a document to the system. Subsequent uploads to the same id will overwrite previous documents.ß",
    "operationId": "uploadDocument",
    "security": [
     {
      "OAuth2Flow": [
       "applications:write",
       "customers:write"
      ]
     }
    ]
   }
  },
  "/v1/deposits": {
   "post": {
    "tags": [
     "Deposits"
    ],
    "summary": "Create Deposit",
    "description": "Create a deposit request for a platform account in order to send funds into the account.",
    "operationId": "createDeposits",
    "security": [
     {
      "OAuth2Flow": [
       "deposits:write"
      ]
     }
    ]
   }
  },
  "/v1/deposits/{deposit_id}/accept": {
   "post": {
    "tags": [
     "Deposits"
    ],
    "summary": "Accept Deposit",
    "description": "Accept a Deposit. This is only needed for `PULL` deposits, `PUSH` deposits do not need to be accepted. On acceptance, this will initiate the funds pull from the source counterparty. It is not reversible",
    "operationId": "acceptDeposit",
    "security": [
     {
      "OAuth2Flow": [
       "deposits:write"
      ]
     }
    ]
   }
  },
  "/v1/customers/{id}/payor": {
   "post": {
    "tags": [
     "Customers"
    ],
    "summary": "Create Payor",
    "description": "Onboard a payor and assign them to a customer. All details are optional barring the ID and First/Last name",
    "operationId": "onboardPayor",
    "security": [
     {
      "OAuth2Flow": [
       "customers:write"
      ]
     }
    ]
   }
  },
  "/v1/customers/{customer_id}/individuals": {
   "post": {
    "tags": [
     "Customers"
    ],
    "summary": "Create Individual",
    "description": "Add a new individual/officer on a corporate customer",
    "operationId": "addIndividual",
    "security": [
     {
      "OAuth2Flow": [
       "customers:write"
      ]
     }
    ]
   }
  },
  "/v1/counterparties": {
   "get": {
    "tags": [
     "Counterparty"
    ],
    "summary": "Retrieve Counterparties",
    "description": "Retrieves a list of counterparties given the filter parameters provided",
    "operationId": "getCounterparties",
    "security": [
     {
      "OAuth2Flow": [
       "accounts:read"
      ]
     }
    ]
   },
   "post": {
    "tags": [
     "Counterparty"
    ],
    "summary": "Create Counterparty",
    "description": "Create a new counterparty for the purpose of pulling funds into the platform or pushing out",
    "operationId": "createCounterparty",
    "security": [
     {
      "OAuth2Flow": [
       "accounts:write"
      ]
     }
    ]
   }
  },
  "/v1/counterparties/{counterparty_id}/link/details": {
   "post": {
    "tags": [
     "Counterparty"
    ],
    "summary": "Retrieve Linking Details",
    "description": "Retrieve the linking instructions for embedding in a UI to launch account linking from providers such as MX or Plaid.",
    "operationId": "getLinkingDetails",
    "security": [
     {
      "OAuth2Flow": [
       "accounts:write"
      ]
     }
    ]
   }
  },
  "/v1/counterparties/{counterparty_id}/link/connect": {
   "post": {
    "tags": [
     "Counterparty"
    ],
    "summary": "Connect Linked Account",
    "description": "Established the connection between a counterparty and external linked account. ",
    "operationId": "connectLinkAccount",
    "security": [
     {
      "OAuth2Flow": [
       "accounts:write"
      ]
     }
    ]
   }
  },
  "/v1/counterparties/{counterparty_id}/link/accounts": {
   "post": {
    "tags": [
     "Counterparty"
    ],
    "summary": "Retrieve Linkable Accounts",
    "description": "Retrieve the accounts that are available for linking for a `LINKED` counterparty via a provider such as MX or Plaid. ",
    "operationId": "getLinkAccounts",
    "security": [
     {
      "OAuth2Flow": [
       "accounts:write"
      ]
     }
    ]
   }
  },
  "/v1/applications": {
   "get": {
    "tags": [
     "Applications"
    ],
    "summary": "Retrieve Applications",
    "description": "Retrieves a list of applications given the filter parameters provided",
    "operationId": "getApplications",
    "security": [
     {
      "OAuth2Flow": [
       "applications:read"
      ]
     }
    ]
   },
   "post": {
    "tags": [
     "Applications"
    ],
    "summary": "Create Application",
    "description": "Start a new application to onboard a person or corporation. Once the application is created, proceed to add individuals and update as needed, and then submit once the status allows for it. ",
    "operationId": "createApplication",
    "security": [
     {
      "OAuth2Flow": [
       "applications:write"
      ]
     }
    ]
   }
  },
  "/v1/applications/{application_id}/submit": {
   "post": {
    "tags": [
     "Applications"
    ],
    "summary": "Submit Application",
    "description": "Submit the application for processing, can only be performed once the application status is  \"READY_FOR_SUBMISSION\".",
    "operationId": "submitApplication",
    "security": [
     {
      "OAuth2Flow": [
       "applications:write"
      ]
     }
    ]
   }
  },
  "/v1/applications/{application_id}/individual": {
   "post": {
    "tags": [
     "Applications"
    ],
    "summary": "Add Individual",
    "description": "Adds an individual to the corporate application. Not applicable for individual applications",
    "operationId": "addIndividualToApplication",
    "security": [
     {
      "OAuth2Flow": [
       "applications:write"
      ]
     }
    ]
   }
  },
  "/v1/applications/{application_id}/accesscode": {
   "post": {
    "tags": [
     "Applications"
    ],
    "summary": "Request Access Code",
    "description": "Generate an access code for use with the rail Customer Onboarding SDK. ",
    "operationId": "createApplicationOneTimeCode",
    "security": [
     {
      "OAuth2Flow": [
       "applications:write"
      ]
     }
    ]
   }
  },
  "/v1/accounts/payments": {
   "get": {
    "tags": [
     "Accounts/Payments"
    ],
    "summary": "Retrieve Accounts",
    "description": "Retrieves a list of accounts given the filter parameters provided",
    "operationId": "getPaymentAccounts",
    "security": [
     {
      "OAuth2Flow": [
       "accounts:read"
      ]
     }
    ]
   },
   "post": {
    "tags": [
     "Accounts/Payments"
    ],
    "summary": "Open Payment Account",
    "description": "Opens a new payment account for a customer. ",
    "operationId": "openPaymentAccount",
    "security": [
     {
      "OAuth2Flow": [
       "accounts:write"
      ]
     }
    ]
   }
  },
  "/v1/accounts/payments/{id}/address": {
   "post": {
    "tags": [
     "Accounts/Payments"
    ],
    "summary": "Request Payment Address",
    "description": "Returns an address that can be used to send deposits to this account. If payor details are provided in the request, the address is also associated to the payor and payment reference ID. \n\nThe [transactions](#operation/getTransactions) listing provides reconciliation details per deposit, including payor information if provided. When auto exchange is enabled, the [settlements](#operation/getSettlement) listing provides a fully breakdown of deposit to exchange and settlement. [...]",
    "operationId": "getPaymentAddress",
    "security": [
     {
      "OAuth2Flow": [
       "accounts:write"
      ]
     }
    ]
   }
  },
  "/v1/accounts/deposits": {
   "get": {
    "tags": [
     "Accounts/Deposits"
    ],
    "summary": "Retrieve Accounts",
    "description": "Retrieves a list of accounts given the filter parameters provided",
    "operationId": "getAccounts",
    "security": [
     {
      "OAuth2Flow": [
       "accounts:read"
      ]
     }
    ]
   },
   "post": {
    "tags": [
     "Accounts/Deposits"
    ],
    "summary": "Open Account",
    "description": "Opens a new account for a customer of a given product type",
    "operationId": "openAccount",
    "security": [
     {
      "OAuth2Flow": [
       "accounts:write"
      ]
     }
    ]
   }
  },
  "/v1/accounts/deposits/{id}/address": {
   "post": {
    "tags": [
     "Accounts/Deposits"
    ],
    "summary": "Request Address",
    "description": "Generates and retrieves a usable deposit address for the Asset Type that is assigned to this account",
    "operationId": "getAddress",
    "security": [
     {
      "OAuth2Flow": [
       "accounts:write"
      ]
     }
    ]
   }
  },
  "/v1/customers/{customer_id}": {
   "get": {
    "tags": [
     "Customers"
    ],
    "summary": "Retrieve Customer",
    "description": "Retrieve customer details",
    "operationId": "getCustomerDetails",
    "security": [
     {
      "OAuth2Flow": [
       "customers:read"
      ]
     }
    ]
   },
   "patch": {
    "tags": [
     "Customers"
    ],
    "summary": "Update Customer ",
    "description": "Update customer details. For individuals (officers) linked to a corporate customer, modify the individual resource directly using [Update Individual](#operation/updateIndividual).",
    "operationId": "updateCustomer",
    "security": [
     {
      "OAuth2Flow": [
       "customers:write"
      ]
     }
    ]
   }
  },
  "/v1/customers/{customer_id}/individuals/{individual_id}": {
   "get": {
    "tags": [
     "Customers"
    ],
    "summary": "Retrieve Individual",
    "description": "Retrieve individual details. This operation is only for corporate customers that have individual officers with access to the account",
    "operationId": "getIndividual",
    "security": [
     {
      "OAuth2Flow": [
       "customers:read"
      ]
     }
    ]
   },
   "patch": {
    "tags": [
     "Customers"
    ],
    "summary": "Update Individual",
    "description": "Update individual details. This operation is only for corporate customers that have individual officers with access to the account",
    "operationId": "updateIndividual",
    "security": [
     {
      "OAuth2Flow": [
       "customers:write"
      ]
     }
    ]
   }
  },
  "/v1/counterparties/{counterparty_id}": {
   "get": {
    "tags": [
     "Counterparty"
    ],
    "summary": "Retrieve Counterparty",
    "description": "Retrieves a list of counterparties given the filter parameters provided",
    "operationId": "getCounterparty",
    "security": [
     {
      "OAuth2Flow": [
       "accounts:read"
      ]
     }
    ]
   },
   "patch": {
    "tags": [
     "Counterparty"
    ],
    "summary": "Update Counterparty ",
    "description": "Update Counterparty details. There are limits to what can be updated once the counterparty has been approved for use. ",
    "operationId": "updateCounterparty",
    "security": [
     {
      "OAuth2Flow": [
       "accounts:write"
      ]
     }
    ]
   }
  },
  "/v1/applications/{application_id}": {
   "get": {
    "tags": [
     "Applications"
    ],
    "summary": "Retrieve Application",
    "description": "Retrieve full details of the  application",
    "operationId": "getApplication",
    "security": [
     {
      "OAuth2Flow": [
       "applications:read"
      ]
     }
    ]
   },
   "patch": {
    "tags": [
     "Applications"
    ],
    "summary": "Update Application ",
    "description": "Update applicant properties. For Individuals attached to a corporation, you much patch the individuals directly using [Update Individual](#operation/updateIndividual_1).",
    "operationId": "updateApplication",
    "security": [
     {
      "OAuth2Flow": [
       "applications:write"
      ]
     }
    ]
   }
  },
  "/v1/applications/{application_id}/individual/{individual_id}": {
   "delete": {
    "tags": [
     "Applications"
    ],
    "summary": "Delete Individual",
    "description": "Deletes an individual from a corporate application. This action is permanent and cannot be reversed. All related details of the individual (including uploaded documents) will also be deleted.",
    "operationId": "deleteIndividual",
    "security": [
     {
      "OAuth2Flow": [
       "applications:write"
      ]
     }
    ]
   },
   "patch": {
    "tags": [
     "Applications"
    ],
    "summary": "Update Individual",
    "description": "Update individual properties. This applies only for corporate applications where individuals associated to the company need to be updated.",
    "operationId": "updateIndividual_1",
    "security": [
     {
      "OAuth2Flow": [
       "applications:write"
      ]
     }
    ]
   }
  },
  "/v1/accounts/payments/{id}": {
   "get": {
    "tags": [
     "Accounts/Payments"
    ],
    "summary": "Retrieve Payment Account",
    "description": "Retrieves the base set of account details for a given account ID",
    "operationId": "getPaymentAccount",
    "security": [
     {
      "OAuth2Flow": [
       "accounts:read"
      ]
     }
    ]
   },
   "patch": {
    "tags": [
     "Accounts/Payments"
    ],
    "summary": "Update Account ",
    "description": "Update an account details. Currently only the account status can be updated.",
    "operationId": "updatePaymentAccount",
    "security": [
     {
      "OAuth2Flow": [
       "accounts:write"
      ]
     }
    ]
   }
  },
  "/v1/accounts/deposits/{id}": {
   "get": {
    "tags": [
     "Accounts/Deposits"
    ],
    "summary": "Retrieve Account",
    "description": "Retrieves the base set of account details for a given account ID",
    "operationId": "getAccount",
    "security": [
     {
      "OAuth2Flow": [
       "accounts:read"
      ]
     }
    ]
   },
   "patch": {
    "tags": [
     "Accounts/Deposits"
    ],
    "summary": "Update Account ",
    "description": "Update an account details. Currently only the account status can be updated.",
    "operationId": "updateDepositAccount",
    "security": [
     {
      "OAuth2Flow": [
       "accounts:write"
      ]
     }
    ]
   }
  },
  "/v1/withdrawals/{withdrawal_id}": {
   "get": {
    "tags": [
     "Withdrawals"
    ],
    "summary": "Retrieve Withdrawal",
    "description": "Retrieves details of a previously requested withdrawal",
    "operationId": "getWithdrawal",
    "security": [
     {
      "OAuth2Flow": [
       "withdrawals:read"
      ]
     }
    ]
   }
  },
  "/v1/withdrawals/{withdrawal_id}/status": {
   "get": {
    "tags": [
     "Withdrawals"
    ],
    "summary": "Retrieve Withdrawal Status",
    "description": "Retrieves status of a previously requested withdrawal",
    "operationId": "getWithdrawalStatus",
    "security": [
     {
      "OAuth2Flow": [
       "withdrawals:read"
      ]
     }
    ]
   }
  },
  "/v1/withdrawals/{withdrawal_id}/receipt": {
   "get": {
    "tags": [
     "Withdrawals"
    ],
    "summary": "Retrieve Withdrawal Receipt",
    "description": "Retrieves a receipt for a previously completed withdrawal.",
    "operationId": "getWithdrawalReceipt",
    "security": [
     {
      "OAuth2Flow": [
       "withdrawals:read"
      ]
     }
    ]
   }
  },
  "/v1/transfers/{transfer_id}": {
   "get": {
    "tags": [
     "Transfers"
    ],
    "summary": "Retrieve Transfer",
    "description": "Retrieves details of a previously requested transfer",
    "operationId": "getTransfer",
    "security": [
     {
      "OAuth2Flow": [
       "transfers:read"
      ]
     }
    ]
   }
  },
  "/v1/transactions": {
   "get": {
    "tags": [
     "Transactions"
    ],
    "summary": "Retrieve Transactions",
    "description": "Retrieves a list of transactions across all accounts given the query parameters provided",
    "operationId": "getTransactions",
    "security": [
     {
      "OAuth2Flow": [
       "accounts:read"
      ]
     }
    ]
   }
  },
  "/v1/transactions/{id}": {
   "get": {
    "tags": [
     "Transactions"
    ],
    "summary": "Retrieve Transaction",
    "description": "Retrieves details of a single transaction",
    "operationId": "getTransaction",
    "security": [
     {
      "OAuth2Flow": [
       "accounts:read"
      ]
     }
    ]
   }
  },
  "/v1/settlements/{settlement_id}": {
   "get": {
    "tags": [
     "Settlements"
    ],
    "summary": "Retrieve Settlement",
    "description": "Returns a detailed breakdown of an outbound settlement by account and customer. Filterable by source and destination accounts.",
    "operationId": "getSettlement",
    "security": [
     {
      "OAuth2Flow": [
       "settlements:read"
      ]
     }
    ]
   }
  },
  "/v1/exchanges/{exchange_id}": {
   "get": {
    "tags": [
     "Exchanges"
    ],
    "summary": "Retrieve Exchange",
    "description": "Retrieves details of a previously requested exchange",
    "operationId": "getExchange",
    "security": [
     {
      "OAuth2Flow": [
       "exchanges:read"
      ]
     }
    ]
   }
  },
  "/v1/documents/{document_id}/download": {
   "get": {
    "tags": [
     "Documents"
    ],
    "summary": "Download Document",
    "description": "Downloads a previously upload document",
    "operationId": "downloadDocument",
    "security": [
     {
      "OAuth2Flow": [
       "applications:read",
       "customers:read"
      ]
     }
    ]
   }
  },
  "/v1/deposits/{deposit_id}": {
   "get": {
    "tags": [
     "Deposits"
    ],
    "summary": "Retrieve Deposit",
    "description": "Retrieves details of a previously requested deposit",
    "operationId": "getDeposit",
    "security": [
     {
      "OAuth2Flow": [
       "deposits:read"
      ]
     }
    ]
   }
  },
  "/v1/customers": {
   "get": {
    "tags": [
     "Customers"
    ],
    "summary": "Retrieve Customers",
    "description": "Retrieve customers matching the provided query parameters ",
    "operationId": "getCustomers",
    "security": [
     {
      "OAuth2Flow": [
       "customers:read"
      ]
     }
    ]
   }
  },
  "/v1/applications/{application_id}/status": {
   "get": {
    "tags": [
     "Applications"
    ],
    "summary": "Retrieve Application Status",
    "description": "Retrieve the detailed status of an application ",
    "operationId": "getApplicationStatus",
    "security": [
     {
      "OAuth2Flow": [
       "applications:read"
      ]
     }
    ]
   }
  },
  "/v1/accounts/payments/{id}/transactions": {
   "get": {
    "tags": [
     "Accounts/Payments"
    ],
    "summary": "Retrieve Transactions",
    "description": "Retrieves all transactions under the given account",
    "operationId": "getPaymentAccountTransactions",
    "security": [
     {
      "OAuth2Flow": [
       "accounts:read"
      ]
     }
    ]
   }
  },
  "/v1/accounts/payments/{id}/transactions/{id}": {
   "get": {
    "tags": [
     "Accounts/Payments"
    ],
    "summary": "Retrieve Transaction",
    "description": "Retrieves details of a single transaction under the given account",
    "operationId": "getPaymentAccountTransaction",
    "security": [
     {
      "OAuth2Flow": [
       "accounts:read"
      ]
     }
    ]
   }
  },
  "/v1/accounts/deposits/{id}/transactions": {
   "get": {
    "tags": [
     "Accounts/Deposits"
    ],
    "summary": "Retrieve Transactions",
    "description": "Retrieves all transactions under the given account",
    "operationId": "getTransactions_1",
    "security": [
     {
      "OAuth2Flow": [
       "accounts:read"
      ]
     }
    ]
   }
  },
  "/v1/accounts/deposits/{id}/transactions/{id}": {
   "get": {
    "tags": [
     "Accounts/Deposits"
    ],
    "summary": "Retrieve Transaction",
    "description": "Retrieves details of a single transaction under the given account",
    "operationId": "getTransaction_1",
    "security": [
     {
      "OAuth2Flow": [
       "accounts:read"
      ]
     }
    ]
   }
  },
  "/v1/subscriptions/{subscription_id}": {
   "delete": {
    "tags": [
     "Subscriptions (Webhooks)"
    ],
    "summary": "Delete Subscription",
    "description": "Delete an existing subscription",
    "operationId": "deleteSubscription",
    "security": [
     {
      "OAuth2Flow": [
       "subscriptions:write"
      ]
     }
    ]
   }
  }
 },
 "components": {
  "securitySchemes": {
   "OAuth2Flow": {
    "type": "oauth2",
    "flows": {
     "clientCredentials": {
      "tokenUrl": "https://auth.layer2financial.com/oauth2/ausbdqlx69rH6OjWd696/v1/token",
      "scopes": {
       "customers:read": "View Customer Data",
       "customers:write": "Create and Modify Customer Related Data",
       "accounts:read": "View Account Data",
       "accounts:write": "Create and Modify Account Related Data",
       "settlements:read": "View Settlements Data",
       "applications:read": "View Application Data",
       "applications:write": "Create and Modify Application Related Data",
       "transfers:read": "View Transfers Data",
       "transfers:write": "Create and Modify Transfers Related Data",
       "withdrawals:read": "View Withdrawals Data",
       "withdrawals:write": "Create and Modify Withdrawals Related Data",
       "exchanges:read": "View Exchanges Data",
       "exchanges:write": "Create and Modify Exchange Related Data",
       "deposits:read": "View Deposit Related data",
       "deposits:write": "Create and Modify Deposit Related Data",
       "subscriptions:read": "View Subscription Related data",
       "subscriptions:write": "Create and Modify Subscription Related Data"
      }
     }
    }
   }
  }
 }
}